# Generated by Django 4.2 on 2023-04-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('in_process', 'In Process'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='opened', max_length=10),
        ),
    ]
